/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laboratorio;

import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JLabel;
import static laboratorio.LAB_LDS.ress;

/**
 *
 * @author fabian
 */
public class LAB_LDM extends javax.swing.JFrame {

    /**
     * Creates new form laboratorio3
     */
    public LAB_LDM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LDM01 = new javax.swing.JLabel();
        LDM02 = new javax.swing.JLabel();
        LDM03 = new javax.swing.JLabel();
        LDM04 = new javax.swing.JLabel();
        LDM05 = new javax.swing.JLabel();
        LDM06 = new javax.swing.JLabel();
        LDM07 = new javax.swing.JLabel();
        LDM08 = new javax.swing.JLabel();
        LDM09 = new javax.swing.JLabel();
        LDM10 = new javax.swing.JLabel();
        LDM11 = new javax.swing.JLabel();
        LDM12 = new javax.swing.JLabel();
        LDM13 = new javax.swing.JLabel();
        LDM14 = new javax.swing.JLabel();
        LDM15 = new javax.swing.JLabel();
        LDM16 = new javax.swing.JLabel();
        LDM17 = new javax.swing.JLabel();
        LDM18 = new javax.swing.JLabel();
        LDM19 = new javax.swing.JLabel();
        LDM20 = new javax.swing.JLabel();
        LDM21 = new javax.swing.JLabel();
        LDM22 = new javax.swing.JLabel();
        LDM23 = new javax.swing.JLabel();
        LDM24 = new javax.swing.JLabel();
        jLabel90 = new javax.swing.JLabel();
        LDM25 = new javax.swing.JLabel();
        LDM26 = new javax.swing.JLabel();
        LDM27 = new javax.swing.JLabel();
        LDM28 = new javax.swing.JLabel();
        LDM29 = new javax.swing.JLabel();
        LDM30 = new javax.swing.JLabel();
        LDM31 = new javax.swing.JLabel();
        LDM32 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        INICIO = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        LAB_LDM = new javax.swing.JMenuItem();
        LAB_LDS = new javax.swing.JMenuItem();
        LAB_LAS = new javax.swing.JMenuItem();
        LAB_LPG = new javax.swing.JMenuItem();
        LAB_LSO = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Laboratorio de Dispositivos Moviles", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 0, 14))); // NOI18N

        LDM01.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LDM02.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LDM03.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LDM04.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LDM05.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LDM06.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LDM07.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LDM08.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LDM09.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LDM10.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LDM11.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LDM12.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LDM13.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LDM14.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LDM15.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LDM16.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LDM17.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LDM18.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LDM19.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LDM20.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LDM21.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LDM22.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LDM23.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LDM24.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        jLabel90.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LDM25.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LDM26.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LDM27.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LDM28.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LDM29.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LDM30.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LDM31.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LDM32.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laboratorio/color.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LDM13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LDM14))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LDM09)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LDM10))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LDM05)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LDM06))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LDM01)
                                .addGap(27, 27, 27)
                                .addComponent(LDM02)))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LDM03)
                            .addComponent(LDM07)
                            .addComponent(LDM11)
                            .addComponent(LDM15))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LDM04)
                            .addComponent(LDM08)
                            .addComponent(LDM12)
                            .addComponent(LDM16))
                        .addGap(90, 90, 90)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel90)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LDM17)
                                    .addComponent(LDM21)
                                    .addComponent(LDM25)
                                    .addComponent(LDM29))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(LDM30)
                                        .addGap(18, 18, 18)
                                        .addComponent(LDM31)
                                        .addGap(18, 18, 18)
                                        .addComponent(LDM32))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(LDM26)
                                        .addGap(18, 18, 18)
                                        .addComponent(LDM27)
                                        .addGap(18, 18, 18)
                                        .addComponent(LDM28))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(LDM18)
                                        .addGap(18, 18, 18)
                                        .addComponent(LDM19)
                                        .addGap(18, 18, 18)
                                        .addComponent(LDM20))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(LDM22)
                                        .addGap(18, 18, 18)
                                        .addComponent(LDM23)
                                        .addGap(18, 18, 18)
                                        .addComponent(LDM24)))))))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25)
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LDM04)
                    .addComponent(LDM03)
                    .addComponent(LDM02)
                    .addComponent(LDM01)
                    .addComponent(LDM17)
                    .addComponent(LDM18)
                    .addComponent(LDM19)
                    .addComponent(LDM20))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LDM05)
                    .addComponent(LDM06)
                    .addComponent(LDM07)
                    .addComponent(LDM08)
                    .addComponent(LDM21)
                    .addComponent(jLabel90)
                    .addComponent(LDM22)
                    .addComponent(LDM23)
                    .addComponent(LDM24))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LDM09)
                    .addComponent(LDM10)
                    .addComponent(LDM11)
                    .addComponent(LDM12)
                    .addComponent(LDM25)
                    .addComponent(LDM26)
                    .addComponent(LDM27)
                    .addComponent(LDM28))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LDM32)
                    .addComponent(LDM31)
                    .addComponent(LDM30)
                    .addComponent(LDM13)
                    .addComponent(LDM14)
                    .addComponent(LDM15)
                    .addComponent(LDM16)
                    .addComponent(LDM29))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        jMenu1.setText("Menu");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        INICIO.setText("Inicio");
        INICIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INICIOActionPerformed(evt);
            }
        });
        jMenu1.add(INICIO);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Laboratorios");

        LAB_LDM.setText("LDM");
        LAB_LDM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LAB_LDMActionPerformed(evt);
            }
        });
        jMenu2.add(LAB_LDM);

        LAB_LDS.setText("LDS");
        LAB_LDS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LAB_LDSActionPerformed(evt);
            }
        });
        jMenu2.add(LAB_LDS);

        LAB_LAS.setText("LAS");
        LAB_LAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LAB_LASActionPerformed(evt);
            }
        });
        jMenu2.add(LAB_LAS);

        LAB_LPG.setText("LPG");
        LAB_LPG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LAB_LPGActionPerformed(evt);
            }
        });
        jMenu2.add(LAB_LPG);

        LAB_LSO.setText("LSO");
        LAB_LSO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LAB_LSOActionPerformed(evt);
            }
        });
        jMenu2.add(LAB_LSO);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 13, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void INICIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INICIOActionPerformed
        // TODO add your handling code here:
        login.Paneldecontrol OPEN = new login.Paneldecontrol();
        OPEN.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_INICIOActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
        login.Paneldecontrol OPEN = new login.Paneldecontrol();
        OPEN.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void LAB_LDMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LAB_LDMActionPerformed
        // TODO add your handling code here:
        laboratorio.LAB_LDM OPEN = new laboratorio.LAB_LDM();
        OPEN.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_LAB_LDMActionPerformed

    private void LAB_LDSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LAB_LDSActionPerformed
        // TODO add your handling code here:ç
        laboratorio.LAB_LDS OPEN = new laboratorio.LAB_LDS();
        OPEN.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_LAB_LDSActionPerformed

    private void LAB_LASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LAB_LASActionPerformed
        laboratorio.LAB_LAS OPEN = new laboratorio.LAB_LAS();
        OPEN.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_LAB_LASActionPerformed

    private void LAB_LPGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LAB_LPGActionPerformed
        laboratorio.LAB_LPG OPEN = new laboratorio.LAB_LPG();
        OPEN.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_LAB_LPGActionPerformed

    private void LAB_LSOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LAB_LSOActionPerformed
        laboratorio.LAB_LSO OPEN = new laboratorio.LAB_LSO();
        OPEN.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_LAB_LSOActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LAB_LDM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LAB_LDM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LAB_LDM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LAB_LDM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LAB_LDM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem INICIO;
    private javax.swing.JMenuItem LAB_LAS;
    private javax.swing.JMenuItem LAB_LDM;
    private javax.swing.JMenuItem LAB_LDS;
    private javax.swing.JMenuItem LAB_LPG;
    private javax.swing.JMenuItem LAB_LSO;
    private javax.swing.JLabel LDM01;
    private javax.swing.JLabel LDM02;
    private javax.swing.JLabel LDM03;
    private javax.swing.JLabel LDM04;
    private javax.swing.JLabel LDM05;
    private javax.swing.JLabel LDM06;
    private javax.swing.JLabel LDM07;
    private javax.swing.JLabel LDM08;
    private javax.swing.JLabel LDM09;
    private javax.swing.JLabel LDM10;
    private javax.swing.JLabel LDM11;
    private javax.swing.JLabel LDM12;
    private javax.swing.JLabel LDM13;
    private javax.swing.JLabel LDM14;
    private javax.swing.JLabel LDM15;
    private javax.swing.JLabel LDM16;
    private javax.swing.JLabel LDM17;
    private javax.swing.JLabel LDM18;
    private javax.swing.JLabel LDM19;
    private javax.swing.JLabel LDM20;
    private javax.swing.JLabel LDM21;
    private javax.swing.JLabel LDM22;
    private javax.swing.JLabel LDM23;
    private javax.swing.JLabel LDM24;
    private javax.swing.JLabel LDM25;
    private javax.swing.JLabel LDM26;
    private javax.swing.JLabel LDM27;
    private javax.swing.JLabel LDM28;
    private javax.swing.JLabel LDM29;
    private javax.swing.JLabel LDM30;
    private javax.swing.JLabel LDM31;
    private javax.swing.JLabel LDM32;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
//private String Clave_PC;
//private int  PkID_PC;
//private String Estatus_PC;
//private String Lab_EquipoPc;
//
//    public String getClave_PC() {
//        return Clave_PC;
//    }
//
//    public void setClave_PC(String Clave_PC) {
//        this.Clave_PC = Clave_PC;
//    }
//    
//     private String  PkID_PC;
//     public String getPkID_PC() {
//        return PkID_PC;
//    }
//
//    public void setPkID_PC(String PkID_PC) {
//        this.PkID_PC = PkID_PC;
//    }
//     private String Estatus_PC;
//     public String getEstatus_PC() {
//        return Estatus_PC;
//    }
//
//    public void   setEstatus_PC(String PkID_PC) {
//        this.Estatus_PC =   Estatus_PC;
//    }
//    
//    private String Lab_EquipoPc;
//     public String getLab_EquipoPc() {
//        return Lab_EquipoPc;
//    }
//
//    public void   setLab_EquipoPc(String PkID_PC) {
//        this.Lab_EquipoPc = Lab_EquipoPc;
//    }
//    public void M_tblEquiposPC_Consulta_Estatus(String _Clave_PC) {
//        System.out.println("M_tblEquiposPC_Consulta_Estatus() >>>>>>>>>>>>>>>> " + "CLAVE PC " + " [ " + _Clave_PC + " ] ");
//        try {
//
//            PreparedStatement s = cn.prepareStatement("select pkID_PC,Clave_PC,Estatus_PC,Lab_EquipoPC FROM tblEquiposPC WHERE Clave_PC=?");
//            s.setString(1, _Clave_PC);
//            ress = s.executeQuery();
//            ressmd = ress.getMetaData();
//            while (ress.next()) {
//                setPkID_PC(ress.getInt("pkID_PC"));
//                setClave_PC(ress.getString("Clave_PC"));
//                setEstatus_PC(ress.getString("Estatus_PC"));
//                setLab_EquipoPc(ress.getString("Lab_EquipoPC"));
//
//            }
//        } catch (SQLException e) {
//            System.out.println("ERROR:: M_tblEquiposPC_Consulta_Estatus()::" + e.toString());
//        }       
//    }
//
//    
//    
//       public void Consultas_EquiposPC() {
//        //PC
//        try {
//
//            //Models.M_tblEquiposPC tbl_EquiposPC = new Models.M_tblEquiposPC();
//
//            String EquiposLDM[] = {"LDM01", "LDM02", "LDM03", "LDM04", "LDM05", "LDM06", "LDM07", "LDM08", "LDM09", "LDM10", "LDM11", "LDM12", "LDM13", "LDM14", "LDM15", "LDM16", "LDM17", "LDM18", "LDM19", "LDM20", "LDM21", "LDM22", "LDM23", "LDM24", "LDM25", "LDM26", "LDM27", "LDM28", "LDM29", "LDM30", "LDM31", "LDM32"};
//
//            JLabel[] etiquetas_JL = {LDM01, LDM02, LDM03, LDM04, LDM05, LDM06, LDM07, LDM08, LDM09, LDM10, LDM11, LDM12, LDM13, LDM14, LDM15, LDM16, LDM17, LDM18, LDM19, LDM20, LDM21, LDM22, LDM23, LDM24, LDM25, LDM26, LDM27, LDM28, LDM29, LDM30, LDM31, LDM32,};
//
//            for (int E = 0; E < EquiposLDM.length; E++) {
//                System.out.println(">>>>>> " + EquiposLDM[E]);
//                String VALM = EquiposLDM[E];
//                tbl_EquiposPC.M_tblEquiposPC_Consulta_Estatus(VALM);
//                for (JLabel etiquetas_JL1 : etiquetas_JL) {
//                    System.out.println("ENVIO JLABEL");
//                    Pintar_Estatus(getClave_PC(), tbl_EquiposPC.getEstatus_PC(), etiquetas_JL[E]);
//                }
//            }
//        } catch (Exception e) {
//            System.out.println(":::" + e.toString());
//
//        }
//    }

  public void Pintar_Estatus(String Clave_PC, String Estatus_PC, JLabel PintaEst) {
        System.out.println("");
        System.out.println("APP_Usuarios::Pintar_Estatus");
        System.out.println("");
        System.out.println("" + Clave_PC + "::::::" + Estatus_PC);
        //PC
        if (Clave_PC.equals(Clave_PC)) {
            System.out.println(Clave_PC + ">>> Existe");

            if (null != Estatus_PC) {
                switch (Estatus_PC) {
                    case "Disponible":

                        System.out.println(Clave_PC + ">>> Disponible");
                        PintaEst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_equiposPC/Disponible_EquipoPC.png")));
//                        pintarImagen(PintaEst, img_EPC.PC_Disponible);

                        break;
                    case "Ocupado":

                        System.out.println(Clave_PC + ">>> Ocupado");
                        PintaEst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_equiposPC/Ocupado_EquipoPC.png")));
//                        pintarImagen(PintaEst, img_EPC.PC_Ocupado);

                        break;
                    case "Manteniento":

                        System.out.println(Clave_PC + ">>> Manteniento");
                        PintaEst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_equiposPC/Mantenimiento_EquipoPC.png")));
//                        pintarImagen(PintaEst, img_EPC.PC_Mantenimiento);

                        break;
                    default:
                        break;
                }
            }
        }
    }

}





