/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laboratorio;

import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JLabel;
import static laboratorio.LAB_LDS.ress;

/**
 *
 * @author fabian
 */
public class LAB_LPG extends javax.swing.JFrame {

    /**
     * Creates new form laboratorio
     */
    public LAB_LPG() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LPG01 = new javax.swing.JLabel();
        LPG02 = new javax.swing.JLabel();
        LPG03 = new javax.swing.JLabel();
        LPG04 = new javax.swing.JLabel();
        LPG05 = new javax.swing.JLabel();
        LPG06 = new javax.swing.JLabel();
        LPG07 = new javax.swing.JLabel();
        LPG08 = new javax.swing.JLabel();
        LPG09 = new javax.swing.JLabel();
        LPG10 = new javax.swing.JLabel();
        LPG11 = new javax.swing.JLabel();
        LPG12 = new javax.swing.JLabel();
        LPG13 = new javax.swing.JLabel();
        LPG14 = new javax.swing.JLabel();
        LPG15 = new javax.swing.JLabel();
        LPG16 = new javax.swing.JLabel();
        LPG17 = new javax.swing.JLabel();
        LPG18 = new javax.swing.JLabel();
        LPG19 = new javax.swing.JLabel();
        LPG20 = new javax.swing.JLabel();
        LPG21 = new javax.swing.JLabel();
        LPG22 = new javax.swing.JLabel();
        LPG23 = new javax.swing.JLabel();
        LPG24 = new javax.swing.JLabel();
        LPG25 = new javax.swing.JLabel();
        LPG26 = new javax.swing.JLabel();
        LPG27 = new javax.swing.JLabel();
        LPG28 = new javax.swing.JLabel();
        LPG29 = new javax.swing.JLabel();
        LPG30 = new javax.swing.JLabel();
        LPG31 = new javax.swing.JLabel();
        LPG32 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        INICIO = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        LAB_LDM = new javax.swing.JMenuItem();
        LAB_LDS = new javax.swing.JMenuItem();
        LAB_LAS = new javax.swing.JMenuItem();
        LAB_LPG = new javax.swing.JMenuItem();
        LAB_LSO = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Laboratorio De programación General ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 0, 14))); // NOI18N

        LPG01.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LPG02.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LPG03.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LPG04.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LPG05.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LPG06.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LPG07.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LPG08.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LPG09.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LPG10.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LPG11.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LPG12.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LPG13.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LPG14.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LPG15.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LPG16.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LPG17.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LPG18.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LPG19.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LPG20.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LPG21.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LPG22.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LPG23.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LPG24.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LPG25.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LPG26.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LPG27.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LPG28.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LPG29.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LPG30.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LPG31.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LPG32.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laboratorio/color.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LPG05)
                        .addGap(18, 18, 18)
                        .addComponent(LPG06)
                        .addGap(18, 18, 18)
                        .addComponent(LPG07)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LPG08)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LPG21))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LPG01)
                        .addGap(18, 18, 18)
                        .addComponent(LPG02)
                        .addGap(18, 18, 18)
                        .addComponent(LPG03)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LPG04)
                        .addGap(113, 113, 113)
                        .addComponent(LPG17))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LPG09)
                        .addGap(18, 18, 18)
                        .addComponent(LPG10)
                        .addGap(18, 18, 18)
                        .addComponent(LPG11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LPG12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LPG25))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addGap(63, 63, 63))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LPG13)
                                .addGap(18, 18, 18)
                                .addComponent(LPG14)
                                .addGap(18, 18, 18)
                                .addComponent(LPG15)
                                .addGap(18, 18, 18)
                                .addComponent(LPG16)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LPG29)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(LPG18)
                        .addGap(33, 33, 33)
                        .addComponent(LPG19)
                        .addGap(26, 26, 26)
                        .addComponent(LPG20))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LPG22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LPG23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(LPG30)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(LPG31))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(LPG26)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(LPG27)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LPG24)
                            .addComponent(LPG28)
                            .addComponent(LPG32))))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel25)
                .addGap(79, 79, 79)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LPG04)
                    .addComponent(LPG03)
                    .addComponent(LPG02)
                    .addComponent(LPG01)
                    .addComponent(LPG17)
                    .addComponent(LPG18)
                    .addComponent(LPG19)
                    .addComponent(LPG20))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LPG05)
                    .addComponent(LPG06)
                    .addComponent(LPG07)
                    .addComponent(LPG08)
                    .addComponent(LPG21)
                    .addComponent(LPG22)
                    .addComponent(LPG23)
                    .addComponent(LPG24))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LPG09)
                    .addComponent(LPG10)
                    .addComponent(LPG11)
                    .addComponent(LPG12)
                    .addComponent(LPG25)
                    .addComponent(LPG26)
                    .addComponent(LPG27)
                    .addComponent(LPG28))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LPG13)
                    .addComponent(LPG14)
                    .addComponent(LPG15)
                    .addComponent(LPG16)
                    .addComponent(LPG29)
                    .addComponent(LPG30)
                    .addComponent(LPG31)
                    .addComponent(LPG32))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jMenu1.setText("Menu");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        INICIO.setText("Inicio");
        INICIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INICIOActionPerformed(evt);
            }
        });
        jMenu1.add(INICIO);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Laboratorios");

        LAB_LDM.setText("LDM");
        LAB_LDM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LAB_LDMActionPerformed(evt);
            }
        });
        jMenu2.add(LAB_LDM);

        LAB_LDS.setText("LDS");
        LAB_LDS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LAB_LDSActionPerformed(evt);
            }
        });
        jMenu2.add(LAB_LDS);

        LAB_LAS.setText("LAS");
        LAB_LAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LAB_LASActionPerformed(evt);
            }
        });
        jMenu2.add(LAB_LAS);

        LAB_LPG.setText("LPG");
        LAB_LPG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LAB_LPGActionPerformed(evt);
            }
        });
        jMenu2.add(LAB_LPG);

        LAB_LSO.setText("LSO");
        LAB_LSO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LAB_LSOActionPerformed(evt);
            }
        });
        jMenu2.add(LAB_LSO);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 25, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
        login.Paneldecontrol OPEN = new login.Paneldecontrol();
        OPEN.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jMenu1ActionPerformed

    private void LAB_LDMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LAB_LDMActionPerformed
        // TODO add your handling code here:
        laboratorio.LAB_LDM OPEN = new laboratorio.LAB_LDM();
        OPEN.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_LAB_LDMActionPerformed

    private void LAB_LDSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LAB_LDSActionPerformed
        // TODO add your handling code here:ç
        laboratorio.LAB_LDS OPEN = new laboratorio.LAB_LDS();
        OPEN.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_LAB_LDSActionPerformed

    private void LAB_LPGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LAB_LPGActionPerformed
        laboratorio.LAB_LPG OPEN = new laboratorio.LAB_LPG();
        OPEN.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_LAB_LPGActionPerformed

    private void LAB_LSOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LAB_LSOActionPerformed
        laboratorio.LAB_LSO OPEN = new laboratorio.LAB_LSO();
        OPEN.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_LAB_LSOActionPerformed

    private void INICIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INICIOActionPerformed
        // TODO add your handling code here:
        login.Paneldecontrol OPEN = new login.Paneldecontrol();
        OPEN.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_INICIOActionPerformed

    private void LAB_LASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LAB_LASActionPerformed
        laboratorio.LAB_LAS OPEN = new laboratorio.LAB_LAS();
        OPEN.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_LAB_LASActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LAB_LPG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LAB_LPG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LAB_LPG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LAB_LPG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LAB_LPG().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem INICIO;
    private javax.swing.JMenuItem LAB_LAS;
    private javax.swing.JMenuItem LAB_LDM;
    private javax.swing.JMenuItem LAB_LDS;
    private javax.swing.JMenuItem LAB_LPG;
    private javax.swing.JMenuItem LAB_LSO;
    private javax.swing.JLabel LPG01;
    private javax.swing.JLabel LPG02;
    private javax.swing.JLabel LPG03;
    private javax.swing.JLabel LPG04;
    private javax.swing.JLabel LPG05;
    private javax.swing.JLabel LPG06;
    private javax.swing.JLabel LPG07;
    private javax.swing.JLabel LPG08;
    private javax.swing.JLabel LPG09;
    private javax.swing.JLabel LPG10;
    private javax.swing.JLabel LPG11;
    private javax.swing.JLabel LPG12;
    private javax.swing.JLabel LPG13;
    private javax.swing.JLabel LPG14;
    private javax.swing.JLabel LPG15;
    private javax.swing.JLabel LPG16;
    private javax.swing.JLabel LPG17;
    private javax.swing.JLabel LPG18;
    private javax.swing.JLabel LPG19;
    private javax.swing.JLabel LPG20;
    private javax.swing.JLabel LPG21;
    private javax.swing.JLabel LPG22;
    private javax.swing.JLabel LPG23;
    private javax.swing.JLabel LPG24;
    private javax.swing.JLabel LPG25;
    private javax.swing.JLabel LPG26;
    private javax.swing.JLabel LPG27;
    private javax.swing.JLabel LPG28;
    private javax.swing.JLabel LPG29;
    private javax.swing.JLabel LPG30;
    private javax.swing.JLabel LPG31;
    private javax.swing.JLabel LPG32;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
//private String Clave_PC;
//private int  PkID_PC;
//private String Estatus_PC;
//private String Lab_EquipoPc;
//
//    public String getClave_PC() {
//        return Clave_PC;
//    }
//
//    public void setClave_PC(String Clave_PC) {
//        this.Clave_PC = Clave_PC;
//    }
//    
//     private String  PkID_PC;
//     public String getPkID_PC() {
//        return PkID_PC;
//    }
//
//    public void setPkID_PC(String PkID_PC) {
//        this.PkID_PC = PkID_PC;
//    }
//     private String Estatus_PC;
//     public String getEstatus_PC() {
//        return Estatus_PC;
//    }
//
//    public void   setEstatus_PC(String PkID_PC) {
//        this.Estatus_PC =   Estatus_PC;
//    }
//    
//    private String Lab_EquipoPc;
//     public String getLab_EquipoPc() {
//        return Lab_EquipoPc;
//    }
//
//    public void   setLab_EquipoPc(String PkID_PC) {
//        this.Lab_EquipoPc = Lab_EquipoPc;
//    }
//    public void M_tblEquiposPC_Consulta_Estatus(String _Clave_PC) {
//        System.out.println("M_tblEquiposPC_Consulta_Estatus() >>>>>>>>>>>>>>>> " + "CLAVE PC " + " [ " + _Clave_PC + " ] ");
//        try {
//
//            PreparedStatement s = cn.prepareStatement("select pkID_PC,Clave_PC,Estatus_PC,Lab_EquipoPC FROM tblEquiposPC WHERE Clave_PC=?");
//            s.setString(1, _Clave_PC);
//            ress = s.executeQuery();
//            ressmd = ress.getMetaData();
//            while (ress.next()) {
//                setPkID_PC(ress.getInt("pkID_PC"));
//                setClave_PC(ress.getString("Clave_PC"));
//                setEstatus_PC(ress.getString("Estatus_PC"));
//                setLab_EquipoPc(ress.getString("Lab_EquipoPC"));
//
//            }
//        } catch (SQLException e) {
//            System.out.println("ERROR:: M_tblEquiposPC_Consulta_Estatus()::" + e.toString());
//        }       
//    }
//
//    
//    
//       public void Consultas_EquiposPC() {
//        //PC
//        try {
//
//            //Models.M_tblEquiposPC tbl_EquiposPC = new Models.M_tblEquiposPC();
//
//            String EquiposLPG[] = {"LPG01", "LPG02", "LPG03", "LPG04", "LPG05", "LPG06", "LPG07", "LPG08", "LPG09", "LPG10", "LPG11", "LPG12", "LPG13", "LPG14", "LPG15", "LPG16", "LPG17", "LPG18", "LPG19", "LPG20", "LPG21", "LPG22", "LPG23", "LPG24", "LPG25", "LPG26", "LPG27", "LPG28", "LPG29", "LPG30", "LPG31", "LPG32"};
//
//            JLabel[] etiquetas_JL = {LPG01, LPG02, LPG03, LPG04, LPG05, LPG06, LPG07, LPG08, LPG09, LPG10, LPG11, LPG12, LPG13, LPG14, LPG15, LPG16, LPG17, LPG18, LPG19, LPG20, LPG21, LPG22, LPG23, LPG24, LPG25, LPG26, LPG27, LPG28, LPG29, LPG30, LPG31, LPG32};
//
//            for (int E = 0; E < EquiposLPG.length; E++) {
//                System.out.println(">>>>>> " + EquiposLPG[E]);
//                String VALM = EquiposLPG[E];
//                tbl_EquiposPC.M_tblEquiposPC_Consulta_Estatus(VALM);
//                for (JLabel etiquetas_JL1 : etiquetas_JL) {
//                    System.out.println("ENVIO JLABEL");
//                    Pintar_Estatus(getClave_PC(), tbl_EquiposPC.getEstatus_PC(), etiquetas_JL[E]);
//                }
//            }
//        } catch (Exception e) {
//            System.out.println(":::" + e.toString());
//
//        }
//    }

  public void Pintar_Estatus(String Clave_PC, String Estatus_PC, JLabel PintaEst) {
        System.out.println("");
        System.out.println("APP_Usuarios::Pintar_Estatus");
        System.out.println("");
        System.out.println("" + Clave_PC + "::::::" + Estatus_PC);
        //PC
        if (Clave_PC.equals(Clave_PC)) {
            System.out.println(Clave_PC + ">>> Existe");

            if (null != Estatus_PC) {
                switch (Estatus_PC) {
                    case "Disponible":

                        System.out.println(Clave_PC + ">>> Disponible");
                        PintaEst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_equiposPC/Disponible_EquipoPC.png")));
//                        pintarImagen(PintaEst, img_EPC.PC_Disponible);

                        break;
                    case "Ocupado":

                        System.out.println(Clave_PC + ">>> Ocupado");
                        PintaEst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_equiposPC/Ocupado_EquipoPC.png")));
//                        pintarImagen(PintaEst, img_EPC.PC_Ocupado);

                        break;
                    case "Manteniento":

                        System.out.println(Clave_PC + ">>> Manteniento");
                        PintaEst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_equiposPC/Mantenimiento_EquipoPC.png")));
//                        pintarImagen(PintaEst, img_EPC.PC_Mantenimiento);

                        break;
                    default:
                        break;
                }
            }
        }
    }

}
