/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laboratorio;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JLabel;


/**
 *
 * @author fabian
 */
public class LAB_LAS extends javax.swing.JFrame {
static PreparedStatement ps;
    static ResultSet ress;
    static ResultSetMetaData ressmd;
    /**
     * Creates new form laboratorio4
     */
    public LAB_LAS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LAS01 = new javax.swing.JLabel();
        LAS02 = new javax.swing.JLabel();
        LAS03 = new javax.swing.JLabel();
        LAS04 = new javax.swing.JLabel();
        LAS05 = new javax.swing.JLabel();
        LAS06 = new javax.swing.JLabel();
        LAS07 = new javax.swing.JLabel();
        LAS08 = new javax.swing.JLabel();
        LAS09 = new javax.swing.JLabel();
        LAS10 = new javax.swing.JLabel();
        LAS11 = new javax.swing.JLabel();
        LAS12 = new javax.swing.JLabel();
        LAS13 = new javax.swing.JLabel();
        LAS14 = new javax.swing.JLabel();
        LAS15 = new javax.swing.JLabel();
        LAS16 = new javax.swing.JLabel();
        LAS17 = new javax.swing.JLabel();
        LAS18 = new javax.swing.JLabel();
        LAS19 = new javax.swing.JLabel();
        LAS20 = new javax.swing.JLabel();
        LAS21 = new javax.swing.JLabel();
        LAS22 = new javax.swing.JLabel();
        LAS23 = new javax.swing.JLabel();
        LAS24 = new javax.swing.JLabel();
        LAS25 = new javax.swing.JLabel();
        LAS26 = new javax.swing.JLabel();
        LAS27 = new javax.swing.JLabel();
        LAS28 = new javax.swing.JLabel();
        LAS29 = new javax.swing.JLabel();
        LAS30 = new javax.swing.JLabel();
        LAS31 = new javax.swing.JLabel();
        LAS32 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        INICIO = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        LAB_LDM = new javax.swing.JMenuItem();
        LAB_LDS = new javax.swing.JMenuItem();
        LAB_LAS = new javax.swing.JMenuItem();
        LAB_LPG = new javax.swing.JMenuItem();
        LAB_LSO = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Laboratorio de Administrador de Servidores", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 0, 14))); // NOI18N

        LAS01.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LAS02.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LAS03.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LAS04.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LAS05.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LAS06.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LAS07.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LAS08.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LAS09.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LAS10.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LAS11.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LAS12.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LAS13.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LAS14.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LAS15.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LAS16.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LAS17.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LAS18.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LAS19.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LAS20.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LAS21.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LAS22.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LAS23.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LAS24.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LAS25.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LAS26.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LAS27.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LAS28.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LAS29.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LAS30.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LAS31.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LAS32.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laboratorio/color.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LAS13)
                            .addComponent(LAS09)
                            .addComponent(LAS05)
                            .addComponent(LAS01))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LAS02)
                                .addGap(18, 18, 18)
                                .addComponent(LAS03)
                                .addGap(26, 26, 26)
                                .addComponent(LAS04))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LAS06)
                                .addGap(18, 18, 18)
                                .addComponent(LAS07)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LAS08))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LAS10)
                                .addGap(18, 18, 18)
                                .addComponent(LAS11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LAS12))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LAS14)
                                .addGap(18, 18, 18)
                                .addComponent(LAS15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LAS16))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(82, 82, 82)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LAS17)
                            .addComponent(LAS21)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LAS29)
                            .addComponent(LAS25))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LAS18)
                            .addComponent(LAS22))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LAS19)
                                .addGap(18, 18, 18)
                                .addComponent(LAS20))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LAS23)
                                .addGap(28, 28, 28)
                                .addComponent(LAS24))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LAS26)
                        .addGap(18, 18, 18)
                        .addComponent(LAS27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LAS28))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LAS30)
                        .addGap(18, 18, 18)
                        .addComponent(LAS31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LAS32)))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25)
                .addGap(81, 81, 81)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LAS04)
                    .addComponent(LAS03)
                    .addComponent(LAS02)
                    .addComponent(LAS01)
                    .addComponent(LAS17)
                    .addComponent(LAS18)
                    .addComponent(LAS19)
                    .addComponent(LAS20))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LAS05)
                    .addComponent(LAS06)
                    .addComponent(LAS07)
                    .addComponent(LAS08)
                    .addComponent(LAS21)
                    .addComponent(LAS22)
                    .addComponent(LAS23)
                    .addComponent(LAS24))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LAS28)
                    .addComponent(LAS27)
                    .addComponent(LAS26)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LAS09)
                            .addComponent(LAS10)
                            .addComponent(LAS11)
                            .addComponent(LAS12)
                            .addComponent(LAS25))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LAS13)
                                    .addComponent(LAS14)
                                    .addComponent(LAS15)
                                    .addComponent(LAS16)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LAS30)
                                    .addComponent(LAS29)
                                    .addComponent(LAS31)
                                    .addComponent(LAS32))))))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jMenu1.setText("Menu");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        INICIO.setText("Inicio");
        INICIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INICIOActionPerformed(evt);
            }
        });
        jMenu1.add(INICIO);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Laboratorios");

        LAB_LDM.setText("LDM");
        LAB_LDM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LAB_LDMActionPerformed(evt);
            }
        });
        jMenu2.add(LAB_LDM);

        LAB_LDS.setText("LDS");
        LAB_LDS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LAB_LDSActionPerformed(evt);
            }
        });
        jMenu2.add(LAB_LDS);

        LAB_LAS.setText("LAS");
        LAB_LAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LAB_LASActionPerformed(evt);
            }
        });
        jMenu2.add(LAB_LAS);

        LAB_LPG.setText("LPG");
        LAB_LPG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LAB_LPGActionPerformed(evt);
            }
        });
        jMenu2.add(LAB_LPG);

        LAB_LSO.setText("LSO");
        LAB_LSO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LAB_LSOActionPerformed(evt);
            }
        });
        jMenu2.add(LAB_LSO);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 16, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.getAccessibleContext().setAccessibleName("Laboratorio de Desarrollo de software");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void INICIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INICIOActionPerformed
        // TODO add your handling code here:
        login.Paneldecontrol OPEN = new login.Paneldecontrol();
        OPEN.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_INICIOActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
        login.Paneldecontrol OPEN = new login.Paneldecontrol();
        OPEN.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void LAB_LDMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LAB_LDMActionPerformed
        // TODO add your handling code here:
        laboratorio.LAB_LDM OPEN = new laboratorio.LAB_LDM();
        OPEN.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_LAB_LDMActionPerformed

    private void LAB_LDSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LAB_LDSActionPerformed
        // TODO add your handling code here:ç
        laboratorio.LAB_LDS OPEN = new laboratorio.LAB_LDS();
        OPEN.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_LAB_LDSActionPerformed

    private void LAB_LASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LAB_LASActionPerformed
        laboratorio.LAB_LAS OPEN = new laboratorio.LAB_LAS();
        OPEN.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_LAB_LASActionPerformed

    private void LAB_LPGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LAB_LPGActionPerformed
        laboratorio.LAB_LPG OPEN = new laboratorio.LAB_LPG();
        OPEN.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_LAB_LPGActionPerformed

    private void LAB_LSOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LAB_LSOActionPerformed
        laboratorio.LAB_LSO OPEN = new laboratorio.LAB_LSO();
        OPEN.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_LAB_LSOActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LAB_LAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LAB_LAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LAB_LAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LAB_LAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LAB_LAS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem INICIO;
    private javax.swing.JMenuItem LAB_LAS;
    private javax.swing.JMenuItem LAB_LDM;
    private javax.swing.JMenuItem LAB_LDS;
    private javax.swing.JMenuItem LAB_LPG;
    private javax.swing.JMenuItem LAB_LSO;
    private javax.swing.JLabel LAS01;
    private javax.swing.JLabel LAS02;
    private javax.swing.JLabel LAS03;
    private javax.swing.JLabel LAS04;
    private javax.swing.JLabel LAS05;
    private javax.swing.JLabel LAS06;
    private javax.swing.JLabel LAS07;
    private javax.swing.JLabel LAS08;
    private javax.swing.JLabel LAS09;
    private javax.swing.JLabel LAS10;
    private javax.swing.JLabel LAS11;
    private javax.swing.JLabel LAS12;
    private javax.swing.JLabel LAS13;
    private javax.swing.JLabel LAS14;
    private javax.swing.JLabel LAS15;
    private javax.swing.JLabel LAS16;
    private javax.swing.JLabel LAS17;
    private javax.swing.JLabel LAS18;
    private javax.swing.JLabel LAS19;
    private javax.swing.JLabel LAS20;
    private javax.swing.JLabel LAS21;
    private javax.swing.JLabel LAS22;
    private javax.swing.JLabel LAS23;
    private javax.swing.JLabel LAS24;
    private javax.swing.JLabel LAS25;
    private javax.swing.JLabel LAS26;
    private javax.swing.JLabel LAS27;
    private javax.swing.JLabel LAS28;
    private javax.swing.JLabel LAS29;
    private javax.swing.JLabel LAS30;
    private javax.swing.JLabel LAS31;
    private javax.swing.JLabel LAS32;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    
    
//    private String Clave_PC;
//    private int  PkID_PC;
//    private String Estatus_PC;
//    private String Lab_EquipoPc;
//
//    public String getClave_PC() {
//        return Clave_PC;
//    }
//
//    public void setClave_PC(String Clave_PC) {
//        this.Clave_PC = Clave_PC;
//    }
//    
//     
//     public String getPkID_PC() {
//        return PkID_PC;
//    }
//
//    public void setPkID_PC(String PkID_PC) {
//        this.PkID_PC = PkID_PC;
//    }
//     public String getEstatus_PC() {
//        return Estatus_PC;
//    }
//
//    public void   setEstatus_PC(String PkID_PC) {
//        this.Estatus_PC =   Estatus_PC;
//    }
//    
//    private String Lab_EquipoPc;
//     public String getLab_EquipoPc() {
//        return Lab_EquipoPc;
//    }
//
//    public void   setLab_EquipoPc(String PkID_PC) {
//        this.Lab_EquipoPc = Lab_EquipoPc;
//    }
//    public void M_tblEquiposPC_Consulta_Estatus(String _Clave_PC) {
//        System.out.println("M_tblEquiposPC_Consulta_Estatus() >>>>>>>>>>>>>>>> " + "CLAVE PC " + " [ " + _Clave_PC + " ] ");
//        try {
//
//            PreparedStatement s = cn.prepareStatement("select pkID_PC,Clave_PC,Estatus_PC,Lab_EquipoPC FROM tblEquiposPC WHERE Clave_PC=?");
//            s.setString(1, _Clave_PC);
//            ress = s.executeQuery();
//            ressmd = ress.getMetaData();
//            while (ress.next()) {
//                setPkID_PC(ress.getInt("pkID_PC"));
//                setClave_PC(ress.getString("Clave_PC"));
//                setEstatus_PC(ress.getString("Estatus_PC"));
//                setLab_EquipoPc(ress.getString("Lab_EquipoPC"));
//
//            }
//        } catch (SQLException e) {
//            System.out.println("ERROR:: M_tblEquiposPC_Consulta_Estatus()::" + e.toString());
//        }       
//    }
//
//    
//    
//       public void Consultas_EquiposPC() {
//        //PC
//        try {
//
//            //Models.M_tblEquiposPC tbl_EquiposPC = new Models.M_tblEquiposPC();
//
//            String EquiposLAS[] = {"LAS01", "LAS02", "LAS03", "LAS04", "LAS05", "LAS06", "LAS07", "LAS08", "LAS09", "LAS10", "LAS11", "LAS12", "LAS13", "LAS14", "LAS15", "LAS16", "LAS17", "LAS18", "LAS19", "LAS20", "LAS21", "LAS22", "LAS23", "LAS24", "LAS25", "LAS26", "LAS27", "LAS28", "LAS29", "LAS30", "LAS31", "LAS32"};
//
//            JLabel[] etiquetas_JL = {LAS01, LAS02, LAS03, LAS04, LAS05, LAS06, LAS07, LAS08, LAS08, LAS10, LAS11, LAS12, LAS13, LAS14, LAS15, LAS16, LAS17, LAS18, LAS19, LAS20, LAS21, LAS22, LAS23, LAS24, LAS25, LAS26, LAS27, LAS28, LAS29, LAS30, LAS31, LAS32};
//
//            for (int E = 0; E < EquiposLAS.length; E++) {
//                System.out.println(">>>>>> " + EquiposLAS[E]);
//                String VALM = EquiposLAS[E];
//                tbl_EquiposPC.M_tblEquiposPC_Consulta_Estatus(VALM);
//                for (JLabel etiquetas_JL1 : etiquetas_JL) {
//                    System.out.println("ENVIO JLABEL");
//                    Pintar_Estatus(getClave_PC(), tbl_EquiposPC.getEstatus_PC(), etiquetas_JL[E]);
//                }
//            }
//        } catch (Exception e) {
//            System.out.println(":::" + e.toString());
//
//        }
//    }
//
//  public void Pintar_Estatus(String Clave_PC, String Estatus_PC, JLabel PintaEst) {
//        System.out.println("");
//        System.out.println("APP_Usuarios::Pintar_Estatus");
//        System.out.println("");
//        System.out.println("" + Clave_PC + "::::::" + Estatus_PC);
//        //PC
//        if (Clave_PC.equals(Clave_PC)) {
//            System.out.println(Clave_PC + ">>> Existe");
//
//            if (null != Estatus_PC) {
//                switch (Estatus_PC) {
//                    case "Disponible":
//
//                        System.out.println(Clave_PC + ">>> Disponible");
//                        PintaEst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_equiposPC/Disponible_EquipoPC.png")));
////                        pintarImagen(PintaEst, img_EPC.PC_Disponible);
//
//                        break;
//                    case "Ocupado":
//
//                        System.out.println(Clave_PC + ">>> Ocupado");
//                        PintaEst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_equiposPC/Ocupado_EquipoPC.png")));
////                        pintarImagen(PintaEst, img_EPC.PC_Ocupado);
//
//                        break;
//                    case "Manteniento":
//
//                        System.out.println(Clave_PC + ">>> Manteniento");
//                        PintaEst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_equiposPC/Mantenimiento_EquipoPC.png")));
////                        pintarImagen(PintaEst, img_EPC.PC_Mantenimiento);
//
//                        break;
//                    default:
//                        break;
//                }
//            }
//        }
//    }

}




