/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laboratorio;

import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JLabel;
import static laboratorio.LAB_LDS.ress;

/**
 *
 * @author fabian
 */
public class LAB_LSO extends javax.swing.JFrame {

    /**
     * Creates new form laboratorio2
     */
    public LAB_LSO() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LSO01 = new javax.swing.JLabel();
        LSO02 = new javax.swing.JLabel();
        LSO03 = new javax.swing.JLabel();
        LSO04 = new javax.swing.JLabel();
        LSO05 = new javax.swing.JLabel();
        LSO06 = new javax.swing.JLabel();
        LSO07 = new javax.swing.JLabel();
        LSO08 = new javax.swing.JLabel();
        LSO09 = new javax.swing.JLabel();
        LSO10 = new javax.swing.JLabel();
        LSO11 = new javax.swing.JLabel();
        LSO12 = new javax.swing.JLabel();
        LSO13 = new javax.swing.JLabel();
        LSO14 = new javax.swing.JLabel();
        LSO15 = new javax.swing.JLabel();
        LSO16 = new javax.swing.JLabel();
        LSO17 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        INICIO = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        LAB_LDM = new javax.swing.JMenuItem();
        LAB_LDS = new javax.swing.JMenuItem();
        LAB_LAS = new javax.swing.JMenuItem();
        LAB_LPG = new javax.swing.JMenuItem();
        LAB_LSO = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Laboratorio de Sistemas Operativos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 0, 14))); // NOI18N
        jPanel1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N

        LSO01.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LSO02.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LSO03.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LSO04.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LSO05.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LSO06.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LSO07.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LSO08.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LSO09.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LSO10.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LSO11.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LSO12.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LSO13.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LSO14.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LSO15.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LSO16.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        LSO17.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        jLabel51.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        jLabel52.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        jLabel53.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        jLabel54.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        jLabel55.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        jLabel56.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        jLabel57.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        jLabel58.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        jLabel59.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        jLabel60.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        jLabel61.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        jLabel62.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        jLabel63.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        jLabel64.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        jLabel65.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabian\\Desktop\\estancia\\compu.png")); // NOI18N

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laboratorio/color.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LSO13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LSO14))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LSO09)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LSO10))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LSO01)
                                .addGap(27, 27, 27)
                                .addComponent(LSO02))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LSO05)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LSO06)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LSO03)
                                .addGap(18, 18, 18)
                                .addComponent(LSO04))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LSO07)
                                .addGap(18, 18, 18)
                                .addComponent(LSO08))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LSO11)
                                .addGap(18, 18, 18)
                                .addComponent(LSO12))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LSO15)
                                .addGap(18, 18, 18)
                                .addComponent(LSO16))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(74, 74, 74)))
                .addGap(130, 130, 130)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel62)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel63))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel58)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel59))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel54)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel55))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LSO17)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel51)))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel52)
                    .addComponent(jLabel56)
                    .addComponent(jLabel60)
                    .addComponent(jLabel64))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel53)
                            .addComponent(jLabel57)
                            .addComponent(jLabel61)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel65)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25)
                .addGap(136, 136, 136)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LSO04)
                    .addComponent(LSO03)
                    .addComponent(LSO02)
                    .addComponent(LSO01)
                    .addComponent(LSO17)
                    .addComponent(jLabel51)
                    .addComponent(jLabel52)
                    .addComponent(jLabel53))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LSO05)
                    .addComponent(LSO06)
                    .addComponent(LSO07)
                    .addComponent(LSO08)
                    .addComponent(jLabel54)
                    .addComponent(jLabel55)
                    .addComponent(jLabel56)
                    .addComponent(jLabel57))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LSO09)
                    .addComponent(LSO10)
                    .addComponent(LSO11)
                    .addComponent(LSO12)
                    .addComponent(jLabel58)
                    .addComponent(jLabel59)
                    .addComponent(jLabel60)
                    .addComponent(jLabel61))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LSO13)
                    .addComponent(LSO14)
                    .addComponent(LSO15)
                    .addComponent(LSO16)
                    .addComponent(jLabel62)
                    .addComponent(jLabel63)
                    .addComponent(jLabel64)
                    .addComponent(jLabel65))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jMenu1.setText("Menu");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        INICIO.setText("Inicio");
        INICIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INICIOActionPerformed(evt);
            }
        });
        jMenu1.add(INICIO);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Laboratorios");

        LAB_LDM.setText("LDM");
        LAB_LDM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LAB_LDMActionPerformed(evt);
            }
        });
        jMenu2.add(LAB_LDM);

        LAB_LDS.setText("LDS");
        LAB_LDS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LAB_LDSActionPerformed(evt);
            }
        });
        jMenu2.add(LAB_LDS);

        LAB_LAS.setText("LAS");
        LAB_LAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LAB_LASActionPerformed(evt);
            }
        });
        jMenu2.add(LAB_LAS);

        LAB_LPG.setText("LPG");
        LAB_LPG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LAB_LPGActionPerformed(evt);
            }
        });
        jMenu2.add(LAB_LPG);

        LAB_LSO.setText("LSO");
        LAB_LSO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LAB_LSOActionPerformed(evt);
            }
        });
        jMenu2.add(LAB_LSO);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void INICIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INICIOActionPerformed
        // TODO add your handling code here:
        login.Paneldecontrol OPEN = new login.Paneldecontrol();
        OPEN.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_INICIOActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
        login.Paneldecontrol OPEN = new login.Paneldecontrol();
        OPEN.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void LAB_LDMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LAB_LDMActionPerformed
        // TODO add your handling code here:
        laboratorio.LAB_LDM OPEN = new laboratorio.LAB_LDM();
        OPEN.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_LAB_LDMActionPerformed

    private void LAB_LDSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LAB_LDSActionPerformed
        // TODO add your handling code here:ç
        laboratorio.LAB_LDS OPEN = new laboratorio.LAB_LDS();
        OPEN.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_LAB_LDSActionPerformed

    private void LAB_LASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LAB_LASActionPerformed
        laboratorio.LAB_LAS OPEN = new laboratorio.LAB_LAS();
        OPEN.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_LAB_LASActionPerformed

    private void LAB_LPGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LAB_LPGActionPerformed
        laboratorio.LAB_LPG OPEN = new laboratorio.LAB_LPG();
        OPEN.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_LAB_LPGActionPerformed

    private void LAB_LSOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LAB_LSOActionPerformed
        laboratorio.LAB_LSO OPEN = new laboratorio.LAB_LSO();
        OPEN.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_LAB_LSOActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LAB_LSO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LAB_LSO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LAB_LSO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LAB_LSO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LAB_LSO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem INICIO;
    private javax.swing.JMenuItem LAB_LAS;
    private javax.swing.JMenuItem LAB_LDM;
    private javax.swing.JMenuItem LAB_LDS;
    private javax.swing.JMenuItem LAB_LPG;
    private javax.swing.JMenuItem LAB_LSO;
    private javax.swing.JLabel LSO01;
    private javax.swing.JLabel LSO02;
    private javax.swing.JLabel LSO03;
    private javax.swing.JLabel LSO04;
    private javax.swing.JLabel LSO05;
    private javax.swing.JLabel LSO06;
    private javax.swing.JLabel LSO07;
    private javax.swing.JLabel LSO08;
    private javax.swing.JLabel LSO09;
    private javax.swing.JLabel LSO10;
    private javax.swing.JLabel LSO11;
    private javax.swing.JLabel LSO12;
    private javax.swing.JLabel LSO13;
    private javax.swing.JLabel LSO14;
    private javax.swing.JLabel LSO15;
    private javax.swing.JLabel LSO16;
    private javax.swing.JLabel LSO17;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
//private String Clave_PC;
//private int  PkID_PC;
//private String Estatus_PC;
//private String Lab_EquipoPc;
//
//    public String getClave_PC() {
//        return Clave_PC;
//    }
//
//    public void setClave_PC(String Clave_PC) {
//        this.Clave_PC = Clave_PC;
//    }
//    
//     private String  PkID_PC;
//     public String getPkID_PC() {
//        return PkID_PC;
//    }
//
//    public void setPkID_PC(String PkID_PC) {
//        this.PkID_PC = PkID_PC;
//    }
//     private String Estatus_PC;
//     public String getEstatus_PC() {
//        return Estatus_PC;
//    }
//
//    public void   setEstatus_PC(String PkID_PC) {
//        this.Estatus_PC =   Estatus_PC;
//    }
//    
//    private String Lab_EquipoPc;
//     public String getLab_EquipoPc() {
//        return Lab_EquipoPc;
//    }
//
//    public void   setLab_EquipoPc(String PkID_PC) {
//        this.Lab_EquipoPc = Lab_EquipoPc;
//    }
//    public void M_tblEquiposPC_Consulta_Estatus(String _Clave_PC) {
//        System.out.println("M_tblEquiposPC_Consulta_Estatus() >>>>>>>>>>>>>>>> " + "CLAVE PC " + " [ " + _Clave_PC + " ] ");
//        try {
//
//            PreparedStatement s = cn.prepareStatement("select pkID_PC,Clave_PC,Estatus_PC,Lab_EquipoPC FROM tblEquiposPC WHERE Clave_PC=?");
//            s.setString(1, _Clave_PC);
//            ress = s.executeQuery();
//            ressmd = ress.getMetaData();
//            while (ress.next()) {
//                setPkID_PC(ress.getInt("pkID_PC"));
//                setClave_PC(ress.getString("Clave_PC"));
//                setEstatus_PC(ress.getString("Estatus_PC"));
//                setLab_EquipoPc(ress.getString("Lab_EquipoPC"));
//
//            }
//        } catch (SQLException e) {
//            System.out.println("ERROR:: M_tblEquiposPC_Consulta_Estatus()::" + e.toString());
//        }       
//    }
//
//    
//    
//       public void Consultas_EquiposPC() {
//        PC
//        try {
//
//            Models.M_tblEquiposPC tbl_EquiposPC = new Models.M_tblEquiposPC();
//
//            String EquiposLSO[] = {"LSO01", "LSO02", "LSO03", "LSO04", "LSO05", "LSO06", "LSO07", "LSO08", "LSO09", "LSO10", "LSO11", "LSO12", "LSO13", "LSO14", "LSO15", "LSO16", "LSO17", "LSO18", "LSO19", "LSO20", "LSO21", "LSO22", "LSO23", "LSO24", "LSO25", "LSO26", "LSO27", "LSO28", "LSO29", "LSO30", "LSO31", "LSO32"};
//
//            JLabel[] etiquetas_JL = {LSO01, LSO02, LSO03, LSO04, LSO05, LSO06, LSO07, LSO08, LSO09, LSO10, LSO11, LSO12, LSO13, LSO14, LSO15, LSO16, LSO17, LSO18, LSO19, LSO20, LSO21, LSO22, LSO23, LSO24, LSO25, LSO26, LSO27, LSO28, LSO29, LSO30, LSO31, LSO32};
//
//            for (int E = 0; E < EquiposLSO.length; E++) {
//                System.out.println(">>>>>> " + EquiposLSO[E]);
//                String VALM = EquiposLSO[E];
//                tbl_EquiposPC.M_tblEquiposPC_Consulta_Estatus(VALM);
//                for (JLabel etiquetas_JL1 : etiquetas_JL) {
//                    System.out.println("ENVIO JLABEL");
//                    Pintar_Estatus(getClave_PC(), tbl_EquiposPC.getEstatus_PC(), etiquetas_JL[E]);
//                }
//            }
//        } catch (Exception e) {
//            System.out.println(":::" + e.toString());
//
//        }
//    }
//
//  public void Pintar_Estatus(String Clave_PC, String Estatus_PC, JLabel PintaEst) {
//        System.out.println("");
//        System.out.println("APP_Usuarios::Pintar_Estatus");
//        System.out.println("");
//        System.out.println("" + Clave_PC + "::::::" + Estatus_PC);
//        PC
//        if (Clave_PC.equals(Clave_PC)) {
//            System.out.println(Clave_PC + ">>> Existe");
//
//            if (null != Estatus_PC) {
//                switch (Estatus_PC) {
//                    case "Disponible":
//
//                        System.out.println(Clave_PC + ">>> Disponible");
//                        PintaEst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_equiposPC/Disponible_EquipoPC.png")));
//                        pintarImagen(PintaEst, img_EPC.PC_Disponible);
//
//                        break;
//                    case "Ocupado":
//
//                        System.out.println(Clave_PC + ">>> Ocupado");
//                        PintaEst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_equiposPC/Ocupado_EquipoPC.png")));
//                        pintarImagen(PintaEst, img_EPC.PC_Ocupado);
//
//                        break;
//                    case "Manteniento":
//
//                        System.out.println(Clave_PC + ">>> Manteniento");
//                        PintaEst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_equiposPC/Mantenimiento_EquipoPC.png")));
//                        pintarImagen(PintaEst, img_EPC.PC_Mantenimiento);
//
//                        break;
//                    default:
//                        break;
//                }
//            }
//        }
//    }

}
