/* To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package administrador;
import javax.swing.JButton;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

import login.PanelAdmi;

import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

import baseDatos.Conexion;

/**
 *
 * @author fabian
 */
public class Clases extends javax.swing.JFrame {

    /**
     * Creates new form Agregar_alumnos
     */
    public Clases() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtLab = new javax.swing.JPanel();
        txtClases = new javax.swing.JLabel();
        txtID_Materias = new javax.swing.JLabel();
        txtIdMateria = new javax.swing.JTextField();
        txtID_Usuarios = new javax.swing.JLabel();
        doa = new javax.swing.JLabel();
        as = new javax.swing.JLabel();
        txtIdLab = new javax.swing.JTextField();
        txtDia = new javax.swing.JTextField();
        txtAsistencia = new javax.swing.JTextField();
        txtID_Clases = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtLab.setBackground(new java.awt.Color(153, 153, 255));

        txtClases.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        txtClases.setText("Clases");

        txtID_Materias.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txtID_Materias.setText("ID_Materias");

        txtID_Usuarios.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txtID_Usuarios.setText("ID_Laboratorio");

        doa.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        doa.setText("Dia");

        as.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        as.setText("Asistencia");

        txtDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiaActionPerformed(evt);
            }
        });

        txtAsistencia.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N

        txtID_Clases.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txtID_Clases.setText("ID_Clases");
        
        JButton btnRegresar = new JButton("Regresar");
        btnRegresar.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		dispose();
        		PanelAdmi ad = new PanelAdmi();
        		ad.setVisible(true);
        	}
        });
        
        scrollPane = new JScrollPane();
        
        JButton btnNewButton = new JButton("Agregar");
        btnNewButton.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		Conexion cn = new Conexion();
        		cn.agregarClases(txtId.getText(),txtIdMateria.getText(),txtIdLab.getText(),txtDia.getText(),txtAsistencia.getText());
				model = cn.mostrarClases();
				table.setModel(model);
        	}
        });

        javax.swing.GroupLayout gl_txtLab = new javax.swing.GroupLayout(txtLab);
        gl_txtLab.setHorizontalGroup(
        	gl_txtLab.createParallelGroup(Alignment.LEADING)
        		.addGroup(gl_txtLab.createSequentialGroup()
        			.addGroup(gl_txtLab.createParallelGroup(Alignment.LEADING)
        				.addGroup(gl_txtLab.createSequentialGroup()
        					.addGap(68)
        					.addComponent(scrollPane, GroupLayout.PREFERRED_SIZE, 394, GroupLayout.PREFERRED_SIZE))
        				.addGroup(gl_txtLab.createSequentialGroup()
        					.addGroup(gl_txtLab.createParallelGroup(Alignment.TRAILING, false)
        						.addGroup(gl_txtLab.createSequentialGroup()
        							.addGap(19)
        							.addComponent(btnRegresar)
        							.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        							.addComponent(txtClases))
        						.addGroup(Alignment.LEADING, gl_txtLab.createSequentialGroup()
        							.addGap(45)
        							.addGroup(gl_txtLab.createParallelGroup(Alignment.TRAILING)
        								.addComponent(txtIdMateria, GroupLayout.PREFERRED_SIZE, 148, GroupLayout.PREFERRED_SIZE)
        								.addGroup(gl_txtLab.createSequentialGroup()
        									.addGroup(gl_txtLab.createParallelGroup(Alignment.LEADING)
        										.addComponent(txtID_Materias, GroupLayout.PREFERRED_SIZE, 120, GroupLayout.PREFERRED_SIZE)
        										.addComponent(doa)
        										.addComponent(txtID_Clases)
        										.addComponent(as, GroupLayout.PREFERRED_SIZE, 97, GroupLayout.PREFERRED_SIZE)
        										.addComponent(txtID_Usuarios, GroupLayout.PREFERRED_SIZE, 112, GroupLayout.PREFERRED_SIZE))
        									.addGap(41)
        									.addGroup(gl_txtLab.createParallelGroup(Alignment.TRAILING)
        										.addComponent(txtId, GroupLayout.PREFERRED_SIZE, 148, GroupLayout.PREFERRED_SIZE)
        										.addComponent(txtIdLab, GroupLayout.PREFERRED_SIZE, 148, GroupLayout.PREFERRED_SIZE)
        										.addComponent(txtDia, GroupLayout.PREFERRED_SIZE, 148, GroupLayout.PREFERRED_SIZE)
        										.addComponent(txtAsistencia, GroupLayout.PREFERRED_SIZE, 148, GroupLayout.PREFERRED_SIZE))))))
        					.addGap(42)
        					.addComponent(btnNewButton)))
        			.addContainerGap(182, Short.MAX_VALUE))
        );
        gl_txtLab.setVerticalGroup(
        	gl_txtLab.createParallelGroup(Alignment.LEADING)
        		.addGroup(gl_txtLab.createSequentialGroup()
        			.addGroup(gl_txtLab.createParallelGroup(Alignment.LEADING)
        				.addGroup(gl_txtLab.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(btnRegresar, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE))
        				.addGroup(gl_txtLab.createSequentialGroup()
        					.addGap(27)
        					.addComponent(txtClases, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)))
        			.addGap(27)
        			.addGroup(gl_txtLab.createParallelGroup(Alignment.BASELINE)
        				.addComponent(txtID_Clases, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
        				.addComponent(txtId, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
        				.addComponent(btnNewButton))
        			.addGap(18)
        			.addGroup(gl_txtLab.createParallelGroup(Alignment.BASELINE)
        				.addComponent(txtID_Materias, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
        				.addComponent(txtIdMateria, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE))
        			.addGap(31)
        			.addGroup(gl_txtLab.createParallelGroup(Alignment.BASELINE)
        				.addComponent(txtID_Usuarios, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
        				.addComponent(txtIdLab, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(gl_txtLab.createParallelGroup(Alignment.LEADING)
        				.addComponent(doa)
        				.addComponent(txtDia, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(gl_txtLab.createParallelGroup(Alignment.TRAILING)
        				.addComponent(as)
        				.addComponent(txtAsistencia, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
        			.addComponent(scrollPane, GroupLayout.PREFERRED_SIZE, 137, GroupLayout.PREFERRED_SIZE)
        			.addGap(60))
        );
        
        model = new DefaultTableModel();
		table = new JTable();
		Conexion cn = new Conexion();
		model = cn.mostrarClases();
		table.setModel(model);
        scrollPane.setViewportView(table);
        txtLab.setLayout(gl_txtLab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(txtLab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(txtLab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DiaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clases().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField txtAsistencia;
    private javax.swing.JTextField txtDia;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIdLab;
    private javax.swing.JTextField txtIdMateria;
    private javax.swing.JPanel txtLab;
    private javax.swing.JLabel as;
    private javax.swing.JLabel txtClases;
    private javax.swing.JLabel doa;
    private javax.swing.JLabel txtID_Clases;
    private javax.swing.JLabel txtID_Materias;
    private javax.swing.JLabel txtID_Usuarios;
    private JScrollPane scrollPane;
    private JTable table;
    private DefaultTableModel model;
}