 /* To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package administrador;
import javax.swing.JButton;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.table.DefaultTableModel;

import baseDatos.Conexion;
import login.PanelAdmi;

import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author fabian
 */
public class Horarios extends javax.swing.JFrame {

    /**
     * Creates new form Agregar_alumnos
     */
    public Horarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtHorarios = new javax.swing.JLabel();
        txtID_Materias = new javax.swing.JLabel();
        ID_Materias = new javax.swing.JTextField();
        txtID_Usuarios = new javax.swing.JLabel();
        txtDia = new javax.swing.JLabel();
        txtHoras = new javax.swing.JLabel();
        ID_Laboratorio = new javax.swing.JTextField();
        Dia = new javax.swing.JTextField();
        Horas = new javax.swing.JTextField();
        txtID_Mantenimientos = new javax.swing.JLabel();
        ID_Horarios = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        txtHorarios.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        txtHorarios.setText("Horarios");

        txtID_Materias.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txtID_Materias.setText("ID_Materias");

        txtID_Usuarios.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txtID_Usuarios.setText("ID_Laboratorio");

        txtDia.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txtDia.setText("Dia");

        txtHoras.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txtHoras.setText("Horas");

        Dia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiaActionPerformed(evt);
            }
        });

        Horas.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N

        txtID_Mantenimientos.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txtID_Mantenimientos.setText("ID_Horarios");
        
        btnNewButton = new JButton("Regresar");
        btnNewButton.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		dispose();
        		PanelAdmi ad = new PanelAdmi();
        		ad.setVisible(true);
        	}
        });
        
        scrollPane = new JScrollPane();
        Conexion cn = new Conexion();
        btnNewButton_1 = new JButton("Agregar");
        btnNewButton_1.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		cn.agregarHorario(ID_Horarios.getText(),ID_Materias.getText(),ID_Laboratorio.getText(),Dia.getText(),Horas.getText());
				model = cn.mostrarHorarios();
				table.setModel(model);
        	}
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGap(278)
        					.addComponent(txtHorarios))
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGap(45)
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        						.addComponent(ID_Materias, GroupLayout.PREFERRED_SIZE, 148, GroupLayout.PREFERRED_SIZE)
        						.addGroup(jPanel1Layout.createSequentialGroup()
        							.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        								.addComponent(txtID_Usuarios, GroupLayout.PREFERRED_SIZE, 112, GroupLayout.PREFERRED_SIZE)
        								.addComponent(txtID_Materias, GroupLayout.PREFERRED_SIZE, 120, GroupLayout.PREFERRED_SIZE)
        								.addComponent(txtDia)
        								.addComponent(txtID_Mantenimientos)
        								.addComponent(txtHoras, GroupLayout.PREFERRED_SIZE, 97, GroupLayout.PREFERRED_SIZE))
        							.addGap(41)
        							.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        								.addComponent(ID_Horarios, GroupLayout.PREFERRED_SIZE, 148, GroupLayout.PREFERRED_SIZE)
        								.addComponent(ID_Laboratorio, GroupLayout.PREFERRED_SIZE, 148, GroupLayout.PREFERRED_SIZE)
        								.addComponent(Dia, GroupLayout.PREFERRED_SIZE, 148, GroupLayout.PREFERRED_SIZE)
        								.addComponent(Horas, GroupLayout.PREFERRED_SIZE, 148, GroupLayout.PREFERRED_SIZE))))
        					.addGap(49)
        					.addComponent(btnNewButton_1))
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGap(25)
        					.addComponent(btnNewButton))
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGap(61)
        					.addComponent(scrollPane, GroupLayout.PREFERRED_SIZE, 419, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap(183, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(14)
        			.addComponent(btnNewButton)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(txtHorarios, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(txtID_Mantenimientos, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
        				.addComponent(ID_Horarios, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
        				.addComponent(btnNewButton_1))
        			.addGap(18)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(txtID_Materias, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
        				.addComponent(ID_Materias, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE))
        			.addGap(31)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(txtID_Usuarios, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
        				.addComponent(ID_Laboratorio, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(txtDia)
        				.addComponent(Dia, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(txtHoras)
        				.addComponent(Horas, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(33)
        			.addComponent(scrollPane, GroupLayout.PREFERRED_SIZE, 165, GroupLayout.PREFERRED_SIZE)
        			.addGap(27))
        );
        
        model= new DefaultTableModel();
		table = new JTable();
		
		model = cn.mostrarHorarios();
		table.setModel(model);
        scrollPane.setViewportView(table);
        jPanel1.setLayout(jPanel1Layout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DiaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Horarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Horarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Horarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Horarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Horarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Dia;
    private javax.swing.JTextField Horas;
    private javax.swing.JTextField ID_Horarios;
    private javax.swing.JTextField ID_Laboratorio;
    private javax.swing.JTextField ID_Materias;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtDia;
    private javax.swing.JLabel txtHorarios;
    private javax.swing.JLabel txtHoras;
    private javax.swing.JLabel txtID_Mantenimientos;
    private javax.swing.JLabel txtID_Materias;
    private javax.swing.JLabel txtID_Usuarios;
    private JButton btnNewButton;
    private JScrollPane scrollPane;
    private JTable table;
    private JButton btnNewButton_1;
    DefaultTableModel model;
   
    // End of variables declaration//GEN-END:variables
}
