 /* To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package administrador;
import javax.swing.JButton;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.table.DefaultTableModel;

import baseDatos.Conexion;
import login.PanelAdmi;

import javax.swing.GroupLayout;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author fabian
 */
public class Observaciones extends javax.swing.JFrame {

    /**
     * Creates new form Agregar_alumnos
     */
    public Observaciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtObservaciones = new javax.swing.JLabel();
        txtID_EquiposPC = new javax.swing.JLabel();
        ID_EquiposPC = new javax.swing.JTextField();
        txtID_Usuarios = new javax.swing.JLabel();
        txtFecha_O = new javax.swing.JLabel();
        txtEstatus = new javax.swing.JLabel();
        ID_Usuarios = new javax.swing.JTextField();
        Fecha_O = new javax.swing.JTextField();
        Observacion = new javax.swing.JTextField();
        txtID_Observaciones = new javax.swing.JLabel();
        ID_Observaciones = new javax.swing.JTextField();
        txtObservacion = new javax.swing.JLabel();
        Estatus = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        txtObservaciones.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        txtObservaciones.setText("Observaciones");

        txtID_EquiposPC.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txtID_EquiposPC.setText("ID_EquiposPC");

        txtID_Usuarios.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txtID_Usuarios.setText("ID_Usuarios");

        txtFecha_O.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txtFecha_O.setText("Fecha_O");

        txtEstatus.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txtEstatus.setText("Estatus");

        Fecha_O.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fecha_OActionPerformed(evt);
            }
        });

        Observacion.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N

        txtID_Observaciones.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txtID_Observaciones.setText("ID_Observaciones");

        txtObservacion.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txtObservacion.setText("Observacion");

        Estatus.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        
        btnNewButton = new JButton("regresar");
        btnNewButton.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		dispose();
        		PanelAdmi ad = new PanelAdmi();
        		ad.setVisible(true);
        	}
        });
        
        scrollPane = new JScrollPane();
        
        btnNewButton_1 = new JButton("Agregar");
        btnNewButton_1.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		cn.agregarObservaciones(ID_Observaciones.getText(),ID_EquiposPC.getText(),ID_Usuarios.getText(),Fecha_O.getText(),Observacion.getText(),Estatus.getText());
				model = cn.mostrarObservaciones();
				table.setModel(model);
        	}
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
        						.addGroup(jPanel1Layout.createSequentialGroup()
        							.addGap(36)
        							.addComponent(txtEstatus)
        							.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        							.addComponent(Estatus, GroupLayout.PREFERRED_SIZE, 148, GroupLayout.PREFERRED_SIZE))
        						.addGroup(jPanel1Layout.createSequentialGroup()
        							.addGap(45)
        							.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        								.addComponent(ID_EquiposPC, GroupLayout.PREFERRED_SIZE, 148, GroupLayout.PREFERRED_SIZE)
        								.addGroup(jPanel1Layout.createSequentialGroup()
        									.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        										.addComponent(txtID_Usuarios, GroupLayout.PREFERRED_SIZE, 112, GroupLayout.PREFERRED_SIZE)
        										.addComponent(txtID_EquiposPC, GroupLayout.PREFERRED_SIZE, 120, GroupLayout.PREFERRED_SIZE)
        										.addComponent(txtFecha_O)
        										.addComponent(txtID_Observaciones)
        										.addComponent(txtObservacion))
        									.addGap(41)
        									.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        										.addComponent(ID_Observaciones, GroupLayout.PREFERRED_SIZE, 148, GroupLayout.PREFERRED_SIZE)
        										.addComponent(ID_Usuarios, GroupLayout.PREFERRED_SIZE, 148, GroupLayout.PREFERRED_SIZE)
        										.addComponent(Fecha_O, GroupLayout.PREFERRED_SIZE, 148, GroupLayout.PREFERRED_SIZE)
        										.addComponent(Observacion, GroupLayout.PREFERRED_SIZE, 148, GroupLayout.PREFERRED_SIZE))))))
        					.addGap(38)
        					.addComponent(btnNewButton_1))
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(btnNewButton)
        					.addGap(188)
        					.addComponent(txtObservaciones))
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(scrollPane, GroupLayout.PREFERRED_SIZE, 492, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap(217, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGap(14)
        					.addComponent(btnNewButton))
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGap(22)
        					.addComponent(txtObservaciones, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)))
        			.addGap(32)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(txtID_Observaciones, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
        				.addComponent(ID_Observaciones, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
        				.addComponent(btnNewButton_1))
        			.addGap(18)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(txtID_EquiposPC, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
        				.addComponent(ID_EquiposPC, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE))
        			.addGap(31)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(txtID_Usuarios, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
        				.addComponent(ID_Usuarios, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(txtFecha_O)
        				.addComponent(Fecha_O, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(26)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(txtObservacion)
        				.addComponent(Observacion, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(40)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(txtEstatus)
        				.addComponent(Estatus, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(scrollPane, GroupLayout.PREFERRED_SIZE, 139, GroupLayout.PREFERRED_SIZE)
        			.addGap(21))
        );
        model = new DefaultTableModel();
		table = new JTable();
		model = cn.mostrarObservaciones();
		table.setModel(model);
		
        scrollPane.setViewportView(table);
        jPanel1.setLayout(jPanel1Layout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Fecha_OActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fecha_OActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Fecha_OActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Observaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Observaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Observaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Observaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Observaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Estatus;
    private javax.swing.JTextField Fecha_O;
    private javax.swing.JTextField ID_EquiposPC;
    private javax.swing.JTextField ID_Observaciones;
    private javax.swing.JTextField ID_Usuarios;
    private javax.swing.JTextField Observacion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtEstatus;
    private javax.swing.JLabel txtFecha_O;
    private javax.swing.JLabel txtID_EquiposPC;
    private javax.swing.JLabel txtID_Observaciones;
    private javax.swing.JLabel txtID_Usuarios;
    private javax.swing.JLabel txtObservacion;
    private javax.swing.JLabel txtObservaciones;
    private JButton btnNewButton;

	DefaultTableModel model;
	Conexion cn = new Conexion();
	private JScrollPane scrollPane;
	private JTable table;
	private JButton btnNewButton_1;
    // End of variables declaration//GEN-END:variables
}
