 /* To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package administrador;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.table.DefaultTableModel;

import baseDatos.Conexion;
import login.PanelAdmi;

import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JRadioButton;
import javax.swing.JPanel;

/**
 *
 * @author fabian
 */
public class Usuarios extends javax.swing.JFrame {

    /**
     * Creates new form Agregar_alumnos
     */
    public Usuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtUsuarios = new javax.swing.JLabel();
        txtID_Usuarios = new javax.swing.JLabel();
        ID_Usuarios = new javax.swing.JTextField();
        txtNombre = new javax.swing.JLabel();
        txtContraseña = new javax.swing.JLabel();
        txtRol = new javax.swing.JLabel();
        Nombre = new javax.swing.JTextField();
        Contrasena = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        txtUsuarios.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        txtUsuarios.setText("Usuarios");

        txtID_Usuarios.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txtID_Usuarios.setText("ID_Usuarios");

        txtNombre.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txtNombre.setText("Nombre");

        txtContraseña.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txtContraseña.setText("Contrase\u00F1a");

        txtRol.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txtRol.setText("Rol");

        Contrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContraseñaActionPerformed(evt);
            }
        });
        
        btnNewButton = new JButton("Regresar");
        btnNewButton.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		dispose();
        		PanelAdmi ad = new PanelAdmi();
        		ad.setVisible(true);
        	}
        });
        
        scrollPane = new JScrollPane();
        
        btnNewButton_1 = new JButton("Agregar");
        btnNewButton_1.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		
        		if(!txtrol.equals("")) {
        			cn.agregarUsuarios(ID_Usuarios.getText(),Nombre.getText(),Contrasena.getText(),txtrol);
    				model = cn.mostrarUsuarios();
    				table.setModel(model);
        		}else {
        			JOptionPane.showMessageDialog(null,"seleccione un rol");
        		}
        		
				
        	}
        });
        
        JPanel panel = new JPanel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(btnNewButton))
        				.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
        					.addGroup(jPanel1Layout.createSequentialGroup()
        						.addGap(45)
        						.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        							.addGroup(jPanel1Layout.createSequentialGroup()
        								.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        									.addComponent(txtNombre, GroupLayout.PREFERRED_SIZE, 112, GroupLayout.PREFERRED_SIZE)
        									.addComponent(txtID_Usuarios, GroupLayout.PREFERRED_SIZE, 120, GroupLayout.PREFERRED_SIZE)
        									.addComponent(txtContraseña))
        								.addPreferredGap(ComponentPlacement.UNRELATED)
        								.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
        									.addComponent(ID_Usuarios)
        									.addComponent(Nombre)
        									.addComponent(Contrasena, GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
        								.addPreferredGap(ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
        								.addComponent(btnNewButton_1))
        							.addComponent(scrollPane, GroupLayout.PREFERRED_SIZE, 372, GroupLayout.PREFERRED_SIZE)
        							.addGroup(jPanel1Layout.createSequentialGroup()
        								.addComponent(txtRol, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE)
        								.addPreferredGap(ComponentPlacement.RELATED)
        								.addComponent(panel, GroupLayout.PREFERRED_SIZE, 261, GroupLayout.PREFERRED_SIZE))))
        					.addGroup(jPanel1Layout.createSequentialGroup()
        						.addGap(293)
        						.addComponent(txtUsuarios, GroupLayout.PREFERRED_SIZE, 143, GroupLayout.PREFERRED_SIZE))))
        			.addContainerGap(320, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(btnNewButton)
        			.addGap(14)
        			.addComponent(txtUsuarios, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
        			.addGap(56)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(txtID_Usuarios, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
        				.addComponent(ID_Usuarios, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
        				.addComponent(btnNewButton_1))
        			.addGap(31)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(txtNombre, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
        				.addComponent(Nombre, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(txtContraseña)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addComponent(Contrasena, GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        					.addGap(2)))
        			.addGap(18)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(txtRol)
        				.addComponent(panel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(30)
        			.addComponent(scrollPane, GroupLayout.PREFERRED_SIZE, 172, GroupLayout.PREFERRED_SIZE)
        			.addGap(24))
        );
        
        JRadioButton rdtAlumno = new JRadioButton("Alumno");
       
        rdtAlumno.setSelected(false);
        panel.add(rdtAlumno);
        
        JRadioButton rdtMaestro = new JRadioButton("Maestro");
        
        rdtMaestro.setSelected(false);
        panel.add(rdtMaestro);
        
        JRadioButton rdtAdministrador = new JRadioButton("Administrador");
        rdtAdministrador.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		rdtMaestro.setSelected(false);
            	rdtAlumno.setSelected(false);
            	txtrol = "administrador";
        	}
        });
        rdtAdministrador.setSelected(false);
        panel.add(rdtAdministrador);
        
        rdtMaestro.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		rdtAlumno.setSelected(false);
            	rdtAdministrador.setSelected(false);
            	txtrol = "maestro";
        	}
        });
        
        rdtAlumno.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		rdtMaestro.setSelected(false);
            	rdtAdministrador.setSelected(false);
            	txtrol = "alumno";
        	}
        });
        
    	model = new DefaultTableModel();
		table = new JTable();
		model = cn.mostrarUsuarios();
		table.setModel(model);
        scrollPane.setViewportView(table);
        jPanel1.setLayout(jPanel1Layout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContraseÃ±aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContraseÃ±aActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Contrasena;
    private javax.swing.JTextField Nombre;
    private javax.swing.JTextField ID_Usuarios;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtContraseña;
    private javax.swing.JLabel txtID_Usuarios;
    private javax.swing.JLabel txtNombre;
    private javax.swing.JLabel txtRol;
    private javax.swing.JLabel txtUsuarios;
    private JButton btnNewButton;
    private JScrollPane scrollPane;
    private JTable table;
    private JButton btnNewButton_1;
    // End of variables declaration//GEN-END:variables

	DefaultTableModel model;
	Conexion cn = new Conexion();
	String txtrol = "";
}
